$script_apache = <<-SCRIPT
apt-get update
apt-get -y install puppet
SCRIPT

$script_ansible = <<-SCRIPT
apt-get update
apt-get -y install software-properties-common
apt-add-repository --yes --update ppa:ansible/ansible
apt-get install -y ansible
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

  config.vm.define "apache" do |apache|

    apache.vm.network "forwarded_port", guest: 80, host: 8888
    apache.vm.network "public_network"

    apache.vm.synced_folder ".", "/vagrant", disabled: true
    apache.vm.synced_folder "./apache", "/vagrant"

    apache.vm.provision "shell", inline: $script_apache
    apache.vm.provision "shell", inline: "cat /vagrant/id_rsa.pub >> .ssh/authorized_keys"
    apache.vm.provision "puppet" do |puppet|
                puppet.manifests_path = "apache/manifests"
                puppet.manifest_file = "apache.pp"
            end
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.hostname = "mysqldb"
    mysql.vm.network "public_network", ip: "192.168.1.70"

    mysql.vm.synced_folder ".", "/vagrant", disabled: true
    mysql.vm.synced_folder "./mysql", "/vagrant"

    mysql.vm.provision "shell", inline: "cat /vagrant/id_rsa.pub >> .ssh/authorized_keys"

  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.network "public_network", ip: "192.168.1.71"

    ansible.vm.provision "shell", inline: $script_ansible

    ansible.vm.synced_folder ".", "/vagrant", disabled: true
    ansible.vm.synced_folder "./ansible", "/vagrant"

    ansible.vm.provision "shell",
        inline: "cp /vagrant/id_rsa  /home/vagrant && \
                chmod 600 /home/vagrant/id_rsa && \
                chown vagrant:vagrant /home/vagrant/id_rsa"

    ansible.vm.provision "shell",
       inline: "ansible-playbook -i /vagrant/hosts /vagrant/playbook.yml"
  end

end
